[package]
name = "essa-function-executor"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.45"
eyre = "0.6.5"
wasmedge-sdk = "0.3.0"
wasmedge-sys = "0.8.0"
wasmedge-types = "0.2.0"
argh = "0.1.6"
# keep in sync with anna-rs
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh.git", rev = "d4b00540cd0faa6ce585e11862cf9740ca226489" }
essa-common = { path = "../common" }
uuid = { version = "0.8.2", features = ["v4"] }
smol = "1.2.5"
log = "0.4.14"
fern = "0.6.0"
chrono = "0.4.19"
serde = { version = "1.0.130", features = ["derive"] }
bincode = "1.3.3"
anna = { git = "https://github.com/essa-project/anna-rs.git" }
